### ISSUE TITLE
Unable to compile with USE_SEGGER_RTT

### ISSUE THREAD

**Issue by onionhammer** [mwaylabs/fruitymesh#82]
See [Terminal.cpp:39](https://github.com/mwaylabs/fruitymesh/blob/35f49b166e36d70e4c53aac63602d74843b889a8/src/utility/Terminal.cpp#L39)

Seems to at least compile with `#include <stdarg.h>` above "SEGGER_RTT.h", but without it I receive 

```
error: 'va_list' was not declared in this scope
```

**Comment by mariusheil** [comment]
ok, so you managed to compile it in the end? Which Compiler and Version die you use?

----- Ursprüngliche Nachricht -----
Von: "onionhammer" <notifications@github.com>
Gesendet: ‎16.‎06.‎2017 05:18
An: "mwaylabs/fruitymesh" <fruitymesh@noreply.github.com>
Cc: "Subscribed" <subscribed@noreply.github.com>
Betreff: [mwaylabs/fruitymesh] Unable to compile with USE_SEGGER_RTT (#82)

See Terminal.cpp:39
Seems to at least compile with #include <stdarg.h> above "SEGGER_RTT.h", but without it I receive
error: 'va_list' was not declared in this scope

**Comment by onionhammer** [comment]
@mariusheil Yes, I did manage to compile using arm gcc 4.9
